#!/bin/sh
#
# Learnintouch Socket server:	Start/stop the Learnintouch Socket server
#

### BEGIN INIT INFO
# Provides:          learnintouch-nodejs
# Required-Start:    $remote_fs $syslog redis
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start learnintouch-nodejs at boot time
# Description:       Enable learnintouch-nodejs provided by daemon.
### END INIT INFO

export PATH=$PATH:/home/stephane/programs/install/bin/

case "$1" in
  start)
#    /home/europasprak/programs/install/lib/node_modules/forever/bin/forever start /home/europasprak/dev/docker/projects/learnintouch/volumes/engine/api/js/socket/elearning-server.js \
#      2>&1 >> /home/europasprak/dev/docker/projects/common/volumes/logs/nodejs.log &
    DEBUG=socket* \
      node /home/europasprak/dev/docker/projects/learnintouch/volumes/engine/api/js/socket/elearning-server.js \
      2>&1 >> /home/europasprak/dev/docker/projects/common/volumes/logs/nodejs.log &
    echo "Starting the Learnintouch Node socket server:"
    ;;
  stop)
    killall node
  	;;
  *)
    echo "Usage: %s {start|stop}\n" "$0"
    exit 1
	;;
esac

exit 0
