#!/bin/sh
#
# Learnintouch Socket server:   Start/stop the Learnintouch Socket server
#

### BEGIN INIT INFO
# Provides:          learnintouchsocket
# Required-Start:    $remote_fs $syslog redis
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start learnintouchsocket at boot time
# Description:       Enable learnintouchsocket provided by daemon.
### END INIT INFO

case "$1" in
  start)
#        forever start /home/stephane/learnintouch/engine/js/socket/elearning-server.js
        /home/stephane/learnintouch/engine/js/socket/start.sh
        echo "Starting the socket server:"
        ;;
  stop)
        ;;
  *)
        echo "Usage: %s {start|stop}\n" "$0"
        exit 1
        ;;
esac

exit 0
