#!/bin/sh
#
# Learnintouch Socket server:	Start/stop the Learnintouch Socket server
#

### BEGIN INIT INFO
# Provides:          learnintouch-nodejs
# Required-Start:    $remote_fs $syslog redis
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start learnintouch-nodejs at boot time
# Description:       Enable learnintouch-nodejs provided by daemon.
### END INIT INFO

case "$1" in
  start)
#        forever start /home/stephane/learnintouch/engine/api/js/socket/elearning-server.js
        /home/stephane/learnintouch/engine/api/js/socket/start.sh
        echo "Starting the socket server:"
        ;;
  stop)
        killall node
  	;;
  *)
        echo "Usage: %s {start|stop}\n" "$0"
        exit 1
	;;
esac

exit 0
