[   0]Modifier une page de questions
[   1]Description:
[   2]Exercice:
[   3]Hauteur maximum du texte:
[   4]Nom:
[   5]Il est possible de spécifier une hauteur maximum pour le texte de la page de questions.\n\nDans ce cas, si le texte ne tient pas dans la hauteur spécifiée alors une barre vertical de défilement est affichée sur la droite du texte.\n\nSi la hauteur maximum n'est pas spécifiée alors le texte est simplement affiché dans la page de questions.\n\nLa hauteur maximum est exprimée en pixels.
[   6]Type de question:
[   7]Il y a plusieurs types de questions.\n\nPar défaut, une liste descendante de réponses est affichée pour les questions à choix multiples et un champ de saisie texte est affiché pour les questions à choix unique.\n\nMais il est possible d'utiliser d'autres types de questions.\n\nVeuillez noter que pour une question n'offrant qu'une seule réponse possible, le type de question est ignoré et un champ de saisie texte est affiché.
[   8]Emplacement d'indice:
[   9]Il y a plusieurs emplacements pour l'indice d'une question.\n\nPar défaut, l'indice est affiché après le champ de la réponse.\n\nMais il est possible de l'afficher:\n\n- après le champ de la réponse\n\n- dans ou après le champ de la réponse\n\n- à la fin de la question\n\n- dans une bulle d'aide
[  11]Il y a plusieurs types de questions.\n\nPar défaut, une liste descendante de réponses est affichée pour les questions à choix multiples et un champ de saisie texte est affiché pour les questions à choix unique.\n\nMais il est possible de:\n\n- afficher une série de boutons radio à la place d'une liste descendante pour afficher directement toutes les réponses offertes\n\n- afficher une série de cases à cocher pour permettre au participant de choisir PLUSIEURS solutions\n\n- afficher une série de cases à cocher pour lesquelles le participant doit fournir TOUTES les solutions (et non pas seulement quelques unes d'entre elles)\n\n- afficher un champ de saisie pour permettre au participant de saisir une réponse au lieu de simplement en choisir une, la réponse donnée par le participant pouvant être une des plusieurs solutions\n\n- afficher un texte à trous, avec une liste descendante de réponses pour chaque trou\n\n- afficher un texte à trous, avec un champ de saisie texte pour chaque trou, dans lequel le participant peut saisir une réponse\n\n- afficher les réponses sous leur question, afin que le participant puisse les glisser et déplacer dans leur question\n\n- afficher toutes les réponses à droite de toutes les questions, afin de permettre au participant de les glisser et déplacer dans les bonnes questions\n\n- afficher les réponses dans un ordre aléatoire afin de permettre au participant de les ordonner pour assembler une phrase\n\n- afficher toutes les réponses sous un texte à trou, pour permettre au participant de les glisser et déplacer dans chaque trou du texte\n\n- afficher toutes les réponses ou les images à droite de toutes les questions, afin de permettre au participant de les glisser et déplacer dans les bonnes questions
[  12]Vous n'avez pas le droit d'utiliser cet exercice.
[  20]Annuler l'opération
[  21]Valider l'opération
[  22]Il est possible de déplacer la page de questions dans un autre exercice.\n\nPour choisir un exercice, veuillez saisir tout ou partie du nom d'un exercice et de faire une recherche basée sur le texte saisi.\n\nLe résultat de la recherche affichera tous les exercices correspondant au texte recherché.
[  23]Video:
[  24]Une video d'un service comme YouTube, Vimeo ou autre, peut être affichée dans la page de question.\n\nLa video est insérée dans la page, par un copier/coller de son code html.
[  25]Url video:
[  26]Une video d'un service comme YouTube, Vimeo ou autre, peut être affichée dans la page de question.\n\nLa video est insérée dans la page, par un copier/coller de son url.\n\nDans ce cas, la video peut être affichée dans la page de question ou est affichée dans une nouvelle page sur le site web hébergeant la video.
[  29]Cacher le texte:
[  30]Par défaut, le texte de la page de l'exercice est affiché dans la fenètre principale du navigateur.\n\nMais il peut être caché et remplacé par un bouton pour permettre au texte d'être affiché.
